### ISSUE TITLE
Maximum number of pages

### ISSUE THREAD

**Issue by guidouil** [imakewebthings/deck.js#182] opened 2015-04-29 09:20 UTC
Hi all,
I am developing a tool to edit decks with a wysiwyg. The customer just told me that he might create some presentation with two thousand files. I tried to recursively create 1000 slide and it allready crash chrome on the deck init...
Is there a way to cut a to big to chew presentation ? and how many slides is the maximum for one presentation ?

**Comment by guidouil** [comment] 2015-04-29 10:12
Just after some test, with 300 slides it still works with lag, with 400 chrome crash. Testing with a Macbook pro i7 / 16 GB RAM.

**Comment by nemec** [comment] 2015-04-29 21:40
Considering all slides are loaded into a single web page all at once, i'm not surprised.

You could try the [lazyload](https://github.com/nemec/deck.lazyload.js) extension which loads each slide from a file (and IIRC unloads them once you're done). I haven't touched it in a while though, so I hope it still works.

**Comment by imakewebthings** [comment] 2015-04-30 04:54
@guidouil @nemec Lazy load extension may work. I'm actually going to close this ticket because it's a dupe of https://github.com/imakewebthings/deck.js/issues/134. There is a discussion there where I suggest a stopgap in the form of a "horizon" extension which I link to in a gist. A core solution is on the roadmap for 2.0.

**Closed by imakewebthings** 2015-04-30 04:54 UTC
